import { createLogger } from '../lib/logger.js';
import { config } from '../startup/env.js';
import { SolverError, ServiceUnavailableError } from '../lib/errors.js';
import { LIMITS, REPORT_FORMATS } from '../lib/constants.js';
import { serializeReportRequest, deserializeReportResponse } from '../lib/serializers.js';

const log = createLogger('ReportService');

/**
 * Request a PDF or HTML report from the Python /report endpoint.
 *
 * @param {object} solution - The full solution object.
 * @param {string} format - 'pdf' or 'html'.
 * @param {object} [options] - { includeGraphs, includeSteps, title }
 * @returns {Promise<object>} { data (base64), format, mimeType, filename }
 */
export async function generateReport(solution, format, options = {}) {
  const reportFormat = format || REPORT_FORMATS.PDF;
  log.info(`Report request: format=${reportFormat}`);

  const body = serializeReportRequest({ solution, format: reportFormat, options });
  const url = `${config.PYTHON_SERVICE_URL}/report`;

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), options.timeout || LIMITS.SOLVE_TIMEOUT_MS);

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    if (!res.ok) {
      const errBody = await res.text().catch(() => '');
      throw new SolverError(
        `Report service returned ${res.status}: ${errBody}`,
        { statusCode: res.status }
      );
    }

    const raw = await res.json();
    const result = deserializeReportResponse(raw);

    if (!result || !result.data) {
      throw new SolverError('Report service returned empty data');
    }

    log.info(`Report generated: format=${result.format}, filename=${result.filename}`);
    return result;
  } catch (err) {
    if (err.name === 'AbortError') {
      throw new SolverError('Report generation timed out');
    }
    if (err instanceof SolverError) throw err;

    // Fallback: generate a basic HTML report on the server if Python is unavailable
    if (reportFormat === REPORT_FORMATS.HTML) {
      log.warn('Python report service unavailable, generating basic HTML fallback');
      return generateFallbackHTML(solution, options);
    }

    throw new ServiceUnavailableError(
      `Report service unreachable: ${err.message}`,
      { url, originalError: err.message }
    );
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * Generate a basic HTML report as a fallback when the Python service is unavailable.
 */
function generateFallbackHTML(solution, options = {}) {
  const title = options.title || 'Math Solution Report';
  const steps = (solution.steps || [])
    .map(
      (s, i) =>
        `<li><strong>Step ${s.number || i + 1}:</strong> ${escapeHtml(s.description || '')}${
          s.expression ? ` <code>${escapeHtml(s.expression)}</code>` : ''
        }</li>`
    )
    .join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }
    h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 0.5rem; }
    .section { margin: 1.5rem 0; }
    .answer { font-size: 1.4rem; color: #27ae60; font-weight: bold; }
    .latex { background: #f8f9fa; padding: 0.5rem 1rem; border-left: 3px solid #3498db; font-family: monospace; }
    ol { line-height: 1.8; }
    .meta { color: #7f8c8d; font-size: 0.9rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="section">
    <h2>Problem</h2>
    <p>${escapeHtml(solution.input || 'N/A')}</p>
    <p class="meta">Type: ${escapeHtml(solution.problemType || 'unknown')}</p>
  </div>
  <div class="section">
    <h2>Answer</h2>
    <p class="answer">${escapeHtml(String(solution.answer || 'N/A'))}</p>
    ${solution.latex ? `<div class="latex">${escapeHtml(solution.latex)}</div>` : ''}
  </div>
  ${
    steps
      ? `<div class="section"><h2>Step-by-Step Solution</h2><ol>${steps}</ol></div>`
      : ''
  }
  ${
    solution.confidence != null
      ? `<div class="section"><h2>Confidence</h2><p>${(solution.confidence * 100).toFixed(1)}%</p></div>`
      : ''
  }
  <footer class="meta">Generated by Arithmetic Math Solver</footer>
</body>
</html>`;

  // Encode to base64
  const data = Buffer.from(html, 'utf-8').toString('base64');

  return {
    data,
    format: 'html',
    mimeType: 'text/html',
    filename: 'report.html',
  };
}

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
