// ui/components/DownloadPanel.js - Download buttons component
import { Tracker } from 'meteor/tracker';
import { Meteor } from 'meteor/meteor';
import { formatAnswer, formatSteps } from '../../lib/formatters';

const DOWNLOAD_OPTIONS = [
  { key: 'pdf', label: 'PDF Report', icon: 'pdf', color: '#ef4444' },
  { key: 'html', label: 'HTML Report', icon: 'html', color: '#f59e0b' },
  { key: 'txt', label: 'Plain Text', icon: 'txt', color: '#10b981' },
  { key: 'png', label: 'Graph PNG', icon: 'png', color: '#6366f1' },
];

export function createDownloadPanel(appState) {
  const panel = document.createElement('div');
  panel.className = 'card download-panel';
  panel.style.display = 'none';

  const title = document.createElement('div');
  title.className = 'card-title';
  title.textContent = 'Download';

  const grid = document.createElement('div');
  grid.className = 'download-grid';

  const buttons = {};

  DOWNLOAD_OPTIONS.forEach(({ key, label, icon, color }) => {
    const btn = document.createElement('button');
    btn.className = 'download-btn';
    btn.dataset.type = key;

    const iconEl = document.createElement('div');
    iconEl.className = 'download-btn-icon';
    iconEl.style.background = color;
    iconEl.textContent = icon.toUpperCase();

    const labelEl = document.createElement('div');
    labelEl.className = 'download-btn-label';
    labelEl.textContent = label;

    btn.appendChild(iconEl);
    btn.appendChild(labelEl);
    grid.appendChild(btn);
    buttons[key] = btn;
  });

  panel.appendChild(title);
  panel.appendChild(grid);

  // --- Event Handlers ---

  // PDF Report
  buttons.pdf.addEventListener('click', () => {
    const result = appState.solverResult.get();
    const problem = appState.currentProblem.get();
    if (!result) return;

    buttons.pdf.classList.add('downloading');
    appState.isLoading.set(true);
    appState.loadingMessage.set('Generating PDF report...');

    Meteor.call('generateReport', {
      format: 'pdf',
      problem,
      result,
    }, (err, reportData) => {
      appState.isLoading.set(false);
      appState.loadingMessage.set('');
      buttons.pdf.classList.remove('downloading');

      if (err) {
        appState.error.set(err.reason || 'Failed to generate PDF report');
        return;
      }

      if (reportData && reportData.data) {
        downloadBase64(reportData.data, reportData.filename || 'arithmetic-report.pdf', 'application/pdf');
      }
    });
  });

  // HTML Report
  buttons.html.addEventListener('click', () => {
    const result = appState.solverResult.get();
    const problem = appState.currentProblem.get();
    if (!result) return;

    buttons.html.classList.add('downloading');
    appState.isLoading.set(true);
    appState.loadingMessage.set('Generating HTML report...');

    Meteor.call('generateReport', {
      format: 'html',
      problem,
      result,
    }, (err, reportData) => {
      appState.isLoading.set(false);
      appState.loadingMessage.set('');
      buttons.html.classList.remove('downloading');

      if (err) {
        appState.error.set(err.reason || 'Failed to generate HTML report');
        return;
      }

      if (reportData && reportData.data) {
        downloadBase64(reportData.data, reportData.filename || 'arithmetic-report.html', 'text/html');
      } else if (reportData && reportData.html) {
        downloadBlob(reportData.html, 'arithmetic-report.html', 'text/html');
      }
    });
  });

  // Plain text - client-side
  buttons.txt.addEventListener('click', () => {
    const result = appState.solverResult.get();
    const problem = appState.currentProblem.get();
    if (!result) return;

    const lines = [];
    lines.push('=== Arithmetic - Solution Report ===');
    lines.push(`Date: ${new Date().toLocaleString()}`);
    lines.push('');
    lines.push(`Problem: ${problem}`);
    lines.push('');
    lines.push(`Answer: ${formatAnswer(result)}`);

    if (result.simplified) lines.push(`Simplified: ${result.simplified}`);
    if (result.decimal || result.approximation) lines.push(`Decimal: ${result.decimal || result.approximation}`);
    if (result.exact) lines.push(`Exact: ${result.exact}`);

    if (result.steps && result.steps.length > 0) {
      lines.push('');
      lines.push('--- Steps ---');
      lines.push(formatSteps(result.steps));
    }

    if (result.source || result.method) {
      lines.push('');
      lines.push(`Method: ${result.source || result.method}`);
    }

    lines.push('');
    lines.push('Generated by Arithmetic');

    downloadBlob(lines.join('\n'), 'arithmetic-solution.txt', 'text/plain');
  });

  // Graph PNG
  buttons.png.addEventListener('click', () => {
    const graphData = appState.graphData.get();
    if (!graphData) {
      appState.error.set('No graph available to download');
      return;
    }

    // Try Plotly export first
    const chartEl = document.querySelector('[id^="plotly-chart-"]');
    if (chartEl && typeof Plotly !== 'undefined') {
      Plotly.downloadImage(chartEl, {
        format: 'png',
        width: 1200,
        height: 800,
        filename: 'arithmetic-graph',
      }).catch(() => {
        // Fallback: server image
        if (graphData.image) {
          downloadBase64(graphData.image, 'arithmetic-graph.png', 'image/png');
        }
      });
    } else if (graphData.image) {
      downloadBase64(graphData.image, 'arithmetic-graph.png', 'image/png');
    }
  });

  // Reactive: show/hide PNG button based on graph availability
  Tracker.autorun(() => {
    const graph = appState.graphData.get();
    buttons.png.style.opacity = graph ? '1' : '0.4';
    buttons.png.style.pointerEvents = graph ? 'auto' : 'none';
  });

  return panel;
}

function downloadBase64(base64Data, filename, mimeType) {
  let data = base64Data;
  // If data includes the data:url prefix, use it directly
  if (!data.startsWith('data:')) {
    data = `data:${mimeType};base64,${data}`;
  }
  const link = document.createElement('a');
  link.href = data;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

function downloadBlob(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
